version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - medilabo

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - medilabo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  back:
    build: ./microservice-back
    container_name: microservice-back
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    environment:
      - SERVER_PORT=${BACKEND_PORT}
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - AUTH_PATIENTS_USERNAME=${AUTH_PATIENTS_USERNAME}
      - AUTH_PATIENTS_PASSWORD=${AUTH_PATIENTS_PASSWORD}
    networks:
      - medilabo

  notes:
    build: ./microservice-notes
    container_name: microservice-notes
    restart: always
    depends_on:
      - mongodb
    ports:
      - "${NOTES_PORT}:${NOTES_PORT}"
    environment:
      - SERVER_PORT=${NOTES_PORT}
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=${MONGO_DATABASE}
      - AUTH_NOTES_USERNAME=${AUTH_NOTES_USERNAME}
      - AUTH_NOTES_PASSWORD=${AUTH_NOTES_PASSWORD}
    networks:
      - medilabo

  diabetes:
    build:
      context: ./microservice-diabetes
      dockerfile: Dockerfile
    container_name: microservice-diabetes
    ports:
      - "${DIABETES_PORT}:${DIABETES_PORT}"
    environment:
      - SERVER_PORT=${DIABETES_PORT}
      - PATIENTS_SERVICE_URL=${PATIENTS_SERVICE_URL}
      - NOTES_SERVICE_URL=${NOTES_SERVICE_URL}
      - GATEWAY_SERVICE_URL=${GATEWAY_SERVICE_URL}
      - AUTH_GATEWAY_USERNAME=${AUTH_GATEWAY_USERNAME}
      - AUTH_GATEWAY_PASSWORD=${AUTH_GATEWAY_PASSWORD}
      - AUTH_PATIENTS_USERNAME=${AUTH_PATIENTS_USERNAME}
      - AUTH_PATIENTS_PASSWORD=${AUTH_PATIENTS_PASSWORD}
      - AUTH_NOTES_USERNAME=${AUTH_NOTES_USERNAME}
      - AUTH_NOTES_PASSWORD=${AUTH_NOTES_PASSWORD}
      - AUTH_DIABETES_USERNAME=${AUTH_DIABETES_USERNAME}
      - AUTH_DIABETES_PASSWORD=${AUTH_DIABETES_PASSWORD}
    depends_on:
      - back
      - notes
    networks:
      - medilabo

  gateway:
    build: ./microservice-gateway
    container_name: microservice-gateway
    hostname: gateway
    restart: always
    depends_on:
      - back
      - notes
      - diabetes
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - SERVER_PORT=${GATEWAY_PORT}
      - GATEWAY_SERVICE_URL=${GATEWAY_SERVICE_URL}
      - PATIENTS_SERVICE_URL=${PATIENTS_SERVICE_URL}
      - NOTES_SERVICE_URL=${NOTES_SERVICE_URL}
      - DIABETES_SERVICE_URL=${DIABETES_SERVICE_URL}
      - AUTH_GATEWAY_USERNAME=${AUTH_GATEWAY_USERNAME}
      - AUTH_GATEWAY_PASSWORD=${AUTH_GATEWAY_PASSWORD}
      - AUTH_PATIENTS_USERNAME=${AUTH_PATIENTS_USERNAME}
      - AUTH_PATIENTS_PASSWORD=${AUTH_PATIENTS_PASSWORD}
      - AUTH_NOTES_USERNAME=${AUTH_NOTES_USERNAME}
      - AUTH_NOTES_PASSWORD=${AUTH_NOTES_PASSWORD}
      - AUTH_DIABETES_USERNAME=${AUTH_DIABETES_USERNAME}
      - AUTH_DIABETES_PASSWORD=${AUTH_DIABETES_PASSWORD}
    networks:
      - medilabo

  front:
    build: ./microservice-front
    container_name: microservice-front
    restart: always
    depends_on:
      - gateway
      - mongodb
    environment:
      - SERVER_PORT=${FRONTEND_PORT}
      - GATEWAY_SERVICE_URL=${GATEWAY_SERVICE_URL}
      - AUTH_GATEWAY_USERNAME=${AUTH_GATEWAY_USERNAME}
      - AUTH_GATEWAY_PASSWORD=${AUTH_GATEWAY_PASSWORD}
      - AUTH_FRONT_USERNAME=${AUTH_FRONT_USERNAME}
      - AUTH_FRONT_PASSWORD=${AUTH_FRONT_PASSWORD}
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=${MONGO_DATABASE}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - medilabo

networks:
  medilabo:
    driver: bridge

volumes:
  db_data:
  mongo_data: