
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: patientdb
      MYSQL_USER: medilabo
      MYSQL_PASSWORD: medipass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  back:
    build: ./microservice-back
    container_name: microservice-back
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/patientdb
      SPRING_DATASOURCE_USERNAME: medilabo
      SPRING_DATASOURCE_PASSWORD: medipass
    ports:
      - "8081:8081"

  gateway:
    build: ./microservice-gateway
    container_name: microservice-gateway
    restart: always
    depends_on:
      - back
    ports:
      - "8080:8080"

  front:
    build: ./microservice-front
    container_name: microservice-front
    restart: always
    depends_on:
      - gateway
    ports:
      - "8082:8082"

volumes:
  db_data:
