
version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root        # mot de passe root obligatoire
      MYSQL_DATABASE: patientdb        # base créée automatiquement
      MYSQL_USER: user                 # utilisateur applicatif
      MYSQL_PASSWORD: password         # mot de passe utilisateur
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  back:
    build:
      context: ./microservice-back     # chemin relatif depuis Projet_9
      dockerfile: Dockerfile
    container_name: back
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/patientdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"

  gateway:
    build:
      context: ./microservice-gateway  # chemin relatif depuis Projet_9
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - back
    ports:
      - "8080:8080"

  front:
    build:
      context: ./microservice-front    # chemin relatif depuis Projet_9
      dockerfile: Dockerfile
    container_name: front
    depends_on:
      - gateway
    ports:
      - "8082:8082"

volumes:
  db_data:
