version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d


  back:
    build: ./microservice-back
    container_name: microservice-back
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    network_mode: host

  notes:
    build: ./microservice-notes
    container_name: microservice-notes
    restart: always
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/${MONGO_DATABASE}
      SPRING_APPLICATION_NAME: note-services
      SERVER_PORT: ${NOTES_PORT}
      AUTH_NOTES_USERNAME: ${AUTH_NOTES_USERNAME}
      AUTH_NOTES_PASSWORD: ${AUTH_NOTES_PASSWORD}
    ports:
      - "8085:8085"
    network_mode: host

  diabetes:
    build:
      context: ./microservice-diabetes
      dockerfile: Dockerfile
    container_name: microservice-diabetes
    ports:
      - "${DIABETES_PORT}:${DIABETES_PORT}"
    environment:
      - PATIENT_SERVICE_URL=https://microservice-back:${BACKEND_PORT}
      - NOTE_SERVICE_URL=https://microservice-notes:${NOTES_PORT}
      - PATIENT_SERVICE_USERNAME=${AUTH_PATIENT_USERNAME}
      - PATIENT_SERVICE_PASSWORD=${AUTH_PATIENT_PASSWORD}
      - NOTE_SERVICE_USERNAME=${AUTH_NOTES_USERNAME}
      - NOTE_SERVICE_PASSWORD=${AUTH_NOTES_PASSWORD}
    depends_on:
      - back
      - notes
    network_mode: host

  gateway:
    build: ./microservice-gateway
    container_name: microservice-gateway
    restart: always
    depends_on:
      - back
      - notes
      - diabetes

    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - PATIENT_CREDENTIALS=${AUTH_PATIENT_USERNAME}:${AUTH_PATIENT_PASSWORD}
      - auth.service.note.credentials=${AUTH_NOTES_USERNAME}:${AUTH_NOTES_PASSWORD}
      - auth.service.diabetes.credentials=${AUTH_DIABETES_USERNAME}:${AUTH_DIABETES_PASSWORD}
      - auth.service.front.credentials=${AUTH_FRONT_USERNAME}:${AUTH_FRONT_PASSWORD}
    network_mode: host

  front:
    build: ./microservice-front
    container_name: microservice-front
    restart: always
    depends_on:
      - gateway
    environment:
      GATEWAY_URL: http://gateway:${GATEWAY_PORT}
      SERVER_PORT: ${FRONTEND_PORT}
      FRONT_SERVICE_USERNAME: ${AUTH_FRONT_USERNAME}
      FRONT_SERVICE_PASSWORD: ${AUTH_FRONT_PASSWORD}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    network_mode: host

volumes:
  db_data:
  mongo_data:

