server:
  port: ${FRONTEND_PORT}

spring:
  application:
    name: front

  thymeleaf:
    cache: false

  main:
    allow-bean-definition-overriding: true

gateway:
  url: ${GATEWAY_SERVICE_URL}

auth:
  front:
    username: ${AUTH_FRONT_USERNAME}
    password: ${AUTH_FRONT_PASSWORD}

  gateway:
    username: ${AUTH_GATEWAY_USERNAME}
    password: ${AUTH_GATEWAY_PASSWORD}

