server:
  port: ${NOTES_PORT}

spring:
  application:
    name: note-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/${MONGO_DATABASE}
      database: ${MONGO_DATABASE}

auth:
  note:
    username: ${AUTH_NOTES_USERNAME}
    password: ${AUTH_NOTES_PASSWORD}