
server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: note-service

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017
      database: notesdb

auth:
  note:
    username: ${AUTH_NOTES_USERNAME:technical_user_notes}
    password: ${AUTH_NOTES_PASSWORD:password}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG