server:
  port: ${DIABETES_PORT}

spring:
  application:
    name: microservice-diabetes

diabetes:
  url: ${DIABETES_SERVICE_URL}


auth:
  gateway:
    username: ${AUTH_GATEWAY_USERNAME}
    password: ${AUTH_GATEWAY_PASSWORD}
  patient:
    username: ${AUTH_PATIENTS_USERNAME}
    password: ${AUTH_PATIENTS_PASSWORD}
  note:
    username: ${AUTH_NOTES_USERNAME}
    password: ${AUTH_NOTES_PASSWORD}
  diabetes:
    username: ${AUTH_DIABETES_USERNAME}
    password: ${AUTH_DIABETES_PASSWORD}


