server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://back:8081
          predicates:
            - Path=/patients/**
        - id: front-service
          uri: http://front:8082
          predicates:
            - Path=/front/**
