server:
  port: 8083

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patient-service/**
          filters:
            - StripPrefix=1

        - id: note-service
          uri: http://localhost:8085
          predicates:
            - Path=/note-service/**
          filters:
            - StripPrefix=1

        - id: diabetes-service
          uri: http://localhost:8084
          predicates:
            - Path=/diabetes-service/**
          filters:
            - StripPrefix=1

internal:
  base-url: http://localhost

auth:
  gateway:
    username: ${AUTH_GATEWAY_USERNAME:technical_user_gateway}
    password: ${AUTH_GATEWAY_PASSWORD:password}
  patient:
    username: ${AUTH_PATIENT_USERNAME:technical_user_patient}
    password: ${AUTH_PATIENT_PASSWORD:password}
  note:
    username: ${AUTH_NOTE_USERNAME:technical_user_notes}
    password: ${AUTH_NOTE_PASSWORD:password}
  diabetes:
    username: ${AUTH_DIABETES_USERNAME:technical_user_diabetes}
    password: ${AUTH_DIABETES_PASSWORD:password}

